### ISSUE TITLE
Tracking issue for release 0.10

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#375]
0.9 was more than 1 year ago, and 0.9.3 was in February, so I think it should be time to do a new release!

The main breaking change I would like to see integrated is #368, please comment here if there is any other breaking change you would like to see in the next release! Non-breaking ones can be introduced in 0.10.1 😃 

---

Here is the list of tasks to be done before the release:

- [x] Create release-0.10 branch & modify VERSION file
- [x] Tag the release candidate
- [x] Check that code builds on https://build.opensuse.org/package/show/home:Luthaf/chemfiles
- [x] Check that code builds on https://github.com/conda-forge/chemfiles-lib-feedstock/
- [x] Check that code builds on https://github.com/JuliaPackaging/Yggdrasil/

- Update bindings
    - [x] Python
        - [x] Update binding
        - [x] Update code
        - [x] Update tests & check coverage
    - [x] Julia
        - [x] Update binding
        - [x] Update code
        - [x] Update tests & check coverage
    - [x] Fortran
        - [x] Update binding
        - [x] Update code
        - [x] Update tests & check coverage
    - [x] Rust
        - [x] Update binding
        - [x] Update code
        - [x] Update tests & check coverage

Please comment below if you want to help and take one of these items on!

----

Final release checklist:

- [x] Release C/C++ lib on build.opensuse.org
- [x] Release C/C++ lib on conda-forge
- [x] Release C/C++ lib on Yggdrasil
- [x] Tag Fortran bindings
- [x] Tag Python bindings
   - [x] build and upload wheels & sdist to PyPi
   - [x] update version on conda (chemfiles-python-feedstock & chemfiles-feedstock)
 - [x] Tag Rust bindings
   - [x] upload on crates.io
 - [x] Tag Julia bindings
     - [x] register on General.jl
 - [x] Make announcement (blog) post
     - [x] share on Twitter
     - [x] share on gitter
  - [x] Check that all documentation have been built and uploaded

**Comment by ezavod** [comment]
Count me in for the Rust bindings. I'll open a PR soon.

**Comment by Luthaf** [comment]
Conda-forge PR: https://github.com/conda-forge/chemfiles-lib-feedstock/pull/38

**Comment by Luthaf** [comment]
Yggdrasil PR: https://github.com/JuliaPackaging/Yggdrasil/pull/2117

**Comment by Luthaf** [comment]
Fortran bindings PR: https://github.com/chemfiles/chemfiles.f03/pull/10

Rust bindings PR by @ezavod: https://github.com/chemfiles/chemfiles.rs/pull/15

**Comment by Luthaf** [comment]
Python bindings PR: https://github.com/chemfiles/chemfiles.py/pull/24

**Comment by Luthaf** [comment]
I've tagged 0.10 on this repository!

**Comment by Luthaf** [comment]
Julia binding PR: https://github.com/chemfiles/Chemfiles.jl/pull/48

**Comment by Luthaf** [comment]
All done and published!
