### ISSUE TITLE
Tracking issue for release 0.10.1

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#415]
It is now time to publish a new release on the 0.10 branch with all the recent bug fixes! As for 0.10.0, I'll use this issue to track all remaining work. If you  want to help, please add a message here picking one item below! There are a few things only I can do, marked with 🔑 below, and a few other only members of the chemfiles organisation can do, marked with 🗝️ below.

## Pre-built chemfiles

- [X] tag the release on chemfiles/chemfiles
- [x] build release on conda-forge: https://github.com/conda-forge/chemfiles-lib-feedstock/pull/41
- [X] try building on Linux: https://build.opensuse.org/package/show/home:Luthaf/chemfiles-staging 🔑
    - [x] a few x86_64 builder failed with "no space left on device"
    - [x] some 32-bit builder fail the `lammps-trajectory` tests because the unit cell matrix differs on the last digits
- [x] release Linux builds: https://build.opensuse.org/package/show/home:Luthaf/chemfiles 🔑
- [X] Build release for Julia (https://github.com/JuliaPackaging/Yggdrasil): https://github.com/JuliaPackaging/Yggdrasil/pull/3369

### Python

- [X] Update the submodule, implement guess_format (https://github.com/chemfiles/chemfiles.py/pull/34)
- [x] Tag release 🗝️
- [x] Create PR on https://github.com/conda-forge/chemfiles-python-feedstock/ (https://github.com/conda-forge/chemfiles-python-feedstock/pull/17)
- [x] Build wheels & upload on PyPI 🔑

### Julia

- [X] Update the submodule, implement guess_format (https://github.com/chemfiles/Chemfiles.jl/pull/50)
- [X] Tag release 🗝️
- [X] Register the new version on https://github.com/JuliaRegistries/General 🗝️ https://github.com/JuliaRegistries/General/pull/41417

### Rust

- [X] Update the submodule, implement guess_format (https://github.com/chemfiles/chemfiles.rs/pull/19)
- [x] Tag release 🗝️
- [x] Release on crates.io 🔑

### Fortran

- [X] Update the submodule, implement guess_format (https://github.com/chemfiles/chemfiles.f03/pull/12)
- [x] Tag release 🗝️
