### ISSUE TITLE
Tracking issue for release 0.10.2

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#436]
If you want to help with the next release, please add a message here picking one item below! There are a few things only I can do, marked with 🔑 below, and a few other only members of the chemfiles organisation can do, marked with 🗝️ below.

## Pre-built chemfiles

- [x] tag the release on chemfiles/chemfiles
- [x] build release on conda-forge (https://github.com/conda-forge/chemfiles-lib-feedstock/pull/44)
- [ ] ~try building on Linux: https://build.opensuse.org/package/show/home:Luthaf/chemfiles-staging 🔑~
    - will not happen, see #437 
- [ ] ~release Linux builds: https://build.opensuse.org/package/show/home:Luthaf/chemfiles 🔑~
    - will not happen, see #437 
- [x] Build release for Julia (https://github.com/JuliaPackaging/Yggdrasil): https://github.com/JuliaPackaging/Yggdrasil/pull/3887

### Python

- [x] Update the submodule, update code, create PR: https://github.com/chemfiles/chemfiles.py/pull/36
- [x] Update code to deal with the new SONAME (i.e. #416)
- [x] Tag release 🗝️
- [x] Create PR on https://github.com/conda-forge/chemfiles-python-feedstock/ (https://github.com/conda-forge/chemfiles-python-feedstock/pull/21)
- [x] Build wheels & upload on PyPI 🔑
    - blocked on https://github.com/chemfiles/chemfiles/pull/438 for sdist

### Julia

- [x] Update Chemfiles_jll version, create PR: https://github.com/chemfiles/Chemfiles.jl/pull/54
- [x] Tag release 🗝️
- [x] Register the new version on https://github.com/JuliaRegistries/General 🗝️ (https://github.com/JuliaRegistries/General/pull/49540)

### Rust

- [X] Update the submodule, update code, create PR: https://github.com/chemfiles/chemfiles.rs/pull/20
- [X] Use pre-built chemfiles downloaded from github when possible (I have a branch doing this locally)
- [x] Tag release 🗝️
- [x] Release on crates.io 🔑
    - blocked on https://github.com/chemfiles/chemfiles/pull/438

### Fortran

- [X] Update the submodule, update code, create PR: https://github.com/chemfiles/chemfiles.f03/pull/13
- [x] Tag release 🗝️

**Comment by Luthaf** [comment]
All done!
