### ISSUE TITLE
Tracking issue for release 0.10.3

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#461]
If you want to help with the next release, please add a message here picking one item below! There are a few things only I can do, marked with 🔑 below, and a few other only members of the chemfiles organisation can do, marked with 🗝️ below.

## Pre-built chemfiles

- [x] update VERSION file and tag the release on chemfiles/chemfiles
- [X] PR on [conda-forge/chemfiles-lib-feedstock](https://github.com/conda-forge/chemfiles-lib-feedstock/): https://github.com/conda-forge/chemfiles-lib-feedstock/pull/48
- [X] Build release for Julia (https://github.com/JuliaPackaging/Yggdrasil): https://github.com/JuliaPackaging/Yggdrasil/pull/5339
- [X] Build and upload to github (https://github.com/chemfiles/chemfiles-prebuilt) https://github.com/chemfiles/chemfiles-prebuilt/releases/tag/v0.10.3

### Python

- [X] Update the submodule, update code, create PR: https://github.com/chemfiles/chemfiles.py/pull/41
- [x] Tag release 🗝️
- [x] Create PR on [conda-forge/chemfiles-python-feedstock](https://github.com/conda-forge/chemfiles-python-feedstock/): https://github.com/conda-forge/chemfiles-python-feedstock/pull/26
- [x] Build wheels & upload on PyPI 🔑

### Julia

- [x] Update Chemfiles_jll version, create PR: https://github.com/chemfiles/Chemfiles.jl/pull/63
- [x] Tag release 🗝️
- [x] Register the new version using https://juliahub.com/ui/Registrator 🗝️: https://github.com/JuliaRegistries/General/pull/67203

### Rust

- [X] Update the submodule, update code, create PR: https://github.com/chemfiles/chemfiles.rs/pull/27
- [x] Tag release 🗝️
- [x] Release on crates.io 🔑

### Fortran

- [X] Update the submodule, update code, create PR: https://github.com/chemfiles/chemfiles.f03/pull/14
- [x] Tag release 🗝️

**Comment by Luthaf** [comment]
Done!
