### ISSUE TITLE
Tracking issue for release 0.10.4

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#475]
If you want to help with the next release, please add a message here picking one item below! There are a few things only I can do, marked with 🔑 below, and a few other only members of the chemfiles organisation can do, marked with 🗝️ below.

## Pre-built chemfiles

- [x] backport remaining PR to the 0.10 release branch: #473
- [x] update VERSION file and tag the release on chemfiles/chemfiles
- [x] PR on [conda-forge/chemfiles-lib-feedstock](https://github.com/conda-forge/chemfiles-lib-feedstock/): https://github.com/conda-forge/chemfiles-lib-feedstock/pull/52
- [x] Build release for Julia (https://github.com/JuliaPackaging/Yggdrasil): https://github.com/JuliaPackaging/Yggdrasil/pull/6720
- [x] Build and upload to github (https://github.com/chemfiles/chemfiles-prebuilt) 

### Python

- [x] Update the submodule, update code, create PR: https://github.com/chemfiles/chemfiles.py/pull/48
- [x] Tag release 🗝️
- [x] Create PR on [conda-forge/chemfiles-python-feedstock](https://github.com/conda-forge/chemfiles-python-feedstock/): https://github.com/conda-forge/chemfiles-python-feedstock/pull/29
- [x] Download wheels from CI for the tag & upload them to PyPI 🔑

### Julia

- [x] Update Chemfiles_jll version, create PR: https://github.com/chemfiles/Chemfiles.jl/pull/75
- [x] Tag release 🗝️
- [x] Register the new version using https://juliahub.com/ui/Registrator 🗝️: https://github.com/JuliaRegistries/General/pull/83767

### Rust

- [x] Update the submodule, update code, create PR: https://github.com/chemfiles/chemfiles.rs/pull/44
- [x] Tag release 🗝️
- [x] Release on crates.io 🔑

### Fortran

- [x] Update the submodule, update code, create PR: https://github.com/chemfiles/chemfiles.f03/pull/16
- [x] Tag release 🗝️

## Documentation

- [x] Check the documentation for all tags, and update it on the website

**Comment by Luthaf** [comment]
Done!
